# ./docker/supervisor/supervisord.conf
[supervisord]
nodaemon=true
user=root

[program:php-fpm]
command=php-fpm -F
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout