-- =========================================================
-- PostgreSQL Database Schema
-- =========================================================

-- =========================================================
-- ENUM TYPES
-- =========================================================

-- CREATE TYPE room_status AS ENUM ('Active', 'Inactive');

-- CREATE TYPE employee_gender AS ENUM ('Male', 'Female');

-- CREATE TYPE employee_status AS ENUM ('Active', 'Inactive');

-- CREATE TYPE student_gender AS ENUM ('Male', 'Female');

-- CREATE TYPE student_status AS ENUM ('draft', 'active', 'cancelled');

-- CREATE TYPE class_status AS ENUM (
--    'Active',
--  'Inactive',
--    'Completed',
--    'Cancelled'
--);

--CREATE TYPE attendance_status AS ENUM (
--    'present',
--    'absent',
--    'late'
--);

--CREATE TYPE invoice_status AS ENUM (
--    'Draft',
--    'Unpaid',
--    'Partial',
--    'Paid',
--    'Cancelled'
--);

--CREATE TYPE payment_status AS ENUM (
--    'Pending',
--    'Completed',
 --   'Failed'
--);

--CREATE TYPE platform_type AS ENUM (
--    'Telegram',
--    'Facebook'
--);

--CREATE TYPE user_reference_type AS ENUM (
--    'Employee',
--    'Student'
--);


-- =========================================================
-- BRANCHES
-- =========================================================

CREATE TABLE tblBranches (
    branch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_code VARCHAR(20) UNIQUE NOT NULL,
    branch_name VARCHAR(150) NOT NULL,
    phone1 VARCHAR(20),
    phone2 VARCHAR(20),
    email VARCHAR(150),
    address TEXT,
    location VARCHAR(20),
    status BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- =========================================================
-- ROOMS
-- =========================================================

CREATE TABLE tblRooms (
    room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_name VARCHAR(50) NOT NULL,
    capacity INT NOT NULL,
    status VARCHAR(50) DEFAULT 'Active'
);


-- =========================================================
-- DEPARTMENTS
-- =========================================================

CREATE TABLE tblDepartments (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_code VARCHAR(20) UNIQUE NOT NULL,
    department_name VARCHAR(100) NOT NULL,
    description TEXT,
    status BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- Positions
-- =========================================================

CREATE TABLE tblPositions (
    position_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    position_code VARCHAR(50) NOT NULL UNIQUE,
    position_name VARCHAR(150) NOT NULL UNIQUE,

    description TEXT,

    status BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================
-- EMPLOYEES
-- =========================================================

CREATE TABLE tblEmployees (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    department_id BIGINT NULL,
    position_id BIGINT NULL,

    first_name_kh VARCHAR(100) NOT NULL,
    last_name_kh VARCHAR(100) NOT NULL,
    first_name_en VARCHAR(100) NOT NULL,
    last_name_en VARCHAR(100) NOT NULL,

    gender VARCHAR(20) NOT NULL,
    dob DATE NOT NULL,

    birth_village VARCHAR(100) NOT NULL,
    birth_commune VARCHAR(100) NOT NULL,
    birth_district VARCHAR(100) NOT NULL,
    birth_province VARCHAR(100) NOT NULL,

    curr_addr_village VARCHAR(100) NOT NULL,
    curr_addr_commune VARCHAR(100) NOT NULL,
    curr_addr_district VARCHAR(100) NOT NULL,
    curr_addr_province VARCHAR(100) NOT NULL,

    phone1 VARCHAR(20) NOT NULL,
    phone2 VARCHAR(20),

    email VARCHAR(150) UNIQUE,

    profile_image VARCHAR(255),

    hired_at DATE NOT NULL,

    status VARCHAR(20) DEFAULT 'Active',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id)
        REFERENCES tblDepartments(department_id)
        ON DELETE SET NULL,

    CONSTRAINT fk_employee_position
        FOREIGN KEY (position_id)
        REFERENCES tblPositions(position_id)
        ON DELETE SET NULL
);

-- =========================================================
-- EMPLOYEE PLATFORMS
-- =========================================================

CREATE TABLE tblEmployeePositionHistory (
    position_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    employee_id BIGINT NOT NULL,
    position_id BIGINT NOT NULL,
    department_id BIGINT NULL,

    start_date DATE NOT NULL,
    end_date DATE NULL,

    remarks TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NULL,

    CONSTRAINT fk_position_history_employee
        FOREIGN KEY (employee_id)
        REFERENCES tblEmployees(employee_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_position_history_position
        FOREIGN KEY (position_id)
        REFERENCES tblPositions(position_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_position_history_department
        FOREIGN KEY (department_id)
        REFERENCES tblDepartments(department_id)
        ON DELETE SET NULL,

    CONSTRAINT fk_position_history_creator
        FOREIGN KEY (created_by)
        REFERENCES tblEmployees(employee_id)
        ON DELETE SET NULL,

    CONSTRAINT chk_position_history_dates
        CHECK (
            end_date IS NULL
            OR end_date >= start_date
        )
);


CREATE INDEX idx_position_history_employee
    ON tblEmployeePositionHistory(employee_id);

CREATE INDEX idx_position_history_department
    ON tblEmployeePositionHistory(department_id);

CREATE INDEX idx_position_history_dates
    ON tblEmployeePositionHistory(start_date, end_date);



-- =========================================================
-- EMPLOYEE PLATFORMS
-- =========================================================

CREATE TABLE tblPlatforms (
    platform_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    employee_id BIGINT NULL,

    platform_type VARCHAR(20) NOT NULL,

    account_name VARCHAR(150),
    account_url VARCHAR(255),
    phone_number VARCHAR(20),

    CONSTRAINT fk_platform_employee
        FOREIGN KEY (employee_id)
        REFERENCES tblEmployees(employee_id)
        ON DELETE SET NULL
);


-- =========================================================
-- STUDENTS
-- =========================================================

CREATE TABLE tblStudents (
    student_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    student_code VARCHAR(100) UNIQUE,

    first_name_kh VARCHAR(100) NOT NULL,
    last_name_kh VARCHAR(100) NOT NULL,

    first_name_en VARCHAR(100) NOT NULL,
    last_name_en VARCHAR(100) NOT NULL,

    gender VARCHAR(20) NOT NULL,
    dob DATE NOT NULL,

    birth_village VARCHAR(100) NOT NULL,
    birth_commune VARCHAR(100) NOT NULL,
    birth_district VARCHAR(100) NOT NULL,
    birth_province VARCHAR(100) NOT NULL,

    curr_addr_village VARCHAR(100) NOT NULL,
    curr_addr_commune VARCHAR(100) NOT NULL,
    curr_addr_district VARCHAR(100) NOT NULL,
    curr_addr_province VARCHAR(100) NOT NULL,

    phone1 VARCHAR(20) NOT NULL,
    phone2 VARCHAR(20),

    email VARCHAR(150),

    profile_image VARCHAR(255),

    academic_year VARCHAR(100) NOT NULL,
    register_at DATE,

    guardian1_name VARCHAR(150) NOT NULL,
    guardian2_name VARCHAR(150) NOT NULL,

    guardian1_relationship VARCHAR(150) NOT NULL,
    guardian2_relationship VARCHAR(150) NOT NULL,

    guardian_curr_addr_village VARCHAR(100) NOT NULL,
    guardian_curr_addr_commune VARCHAR(100) NOT NULL,
    guardian_curr_addr_district VARCHAR(100) NOT NULL,
    guardian_curr_addr_province VARCHAR(100) NOT NULL,

    guardian1_phone VARCHAR(20),
    guardian2_phone VARCHAR(20),

    guardian_email VARCHAR(150),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    created_by BIGINT NULL,

    status VARCHAR(20) DEFAULT 'draft',

    CONSTRAINT fk_student_creator
        FOREIGN KEY (created_by)
        REFERENCES tblEmployees(employee_id)
        ON DELETE SET NULL
);


-- =========================================================
-- SUBJECTS
-- =========================================================

CREATE TABLE tblSubjects (
    subject_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    subject_code VARCHAR(150) NOT NULL UNIQUE,
    subject_name VARCHAR(150) NOT NULL
);

-- =========================================================
-- LEVELS
-- =========================================================

CREATE TABLE tblLevels (
    level_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    level_name VARCHAR(50),

    level_number SMALLINT NOT NULL UNIQUE
);
-- =========================================================
-- COURSES
-- =========================================================

CREATE TABLE tblCourses (
    course_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    course_code VARCHAR(50) NOT NULL UNIQUE,
    course_name VARCHAR(100) NOT NULL,

    subject_id BIGINT NOT NULL,
    level_id BIGINT NOT NULL,

    price DECIMAL(10,2) NOT NULL,
    duration VARCHAR(50),

    CONSTRAINT fk_course_subject
        FOREIGN KEY (subject_id)
        REFERENCES tblSubjects(subject_id),

    CONSTRAINT fk_course_level
        FOREIGN KEY (level_id)
        REFERENCES tblLevels(level_id)
);


-- =========================================================
-- EMPLOYEE SUBJECTS
-- =========================================================

CREATE TABLE tblEmployeeSubjects (
    employee_subject_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    employee_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,

    CONSTRAINT uq_employee_subject
        UNIQUE (employee_id, subject_id),

    CONSTRAINT fk_employee_subject_employee
        FOREIGN KEY (employee_id)
        REFERENCES tblEmployees(employee_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_employee_subject_subject
        FOREIGN KEY (subject_id)
        REFERENCES tblSubjects(subject_id)
        ON DELETE CASCADE
);


-- =========================================================
-- TIME SLOTS
-- =========================================================

CREATE TABLE tblTimeSlots (
    slot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    slot_name VARCHAR(50),

    start_time TIME NOT NULL,
    end_time TIME NOT NULL,

    status room_status DEFAULT 'Active',

    CONSTRAINT uq_time_slot
        UNIQUE (start_time, end_time)
);


-- =========================================================
-- DAYS
-- =========================================================

CREATE TABLE tblDays (
    day_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    day_code VARCHAR(10) NOT NULL UNIQUE,
    day_name VARCHAR(50) NOT NULL,

    sort_order SMALLINT NOT NULL,

    is_active BOOLEAN DEFAULT TRUE
);


-- =========================================================
-- CLASSES
-- =========================================================

CREATE TABLE tblClasses (
    class_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    class_name VARCHAR(100),
    class_code VARCHAR(50) UNIQUE NOT NULL,

    course_id BIGINT NOT NULL,

   
    academic_year VARCHAR(9) NOT NULL,

    max_students INT DEFAULT 50,
    current_students INT DEFAULT 0,

    status VARCHAR(50) DEFAULT 'Active',

    CONSTRAINT fk_class_course
        FOREIGN KEY (course_id)
        REFERENCES tblCourses(course_id),

    CONSTRAINT fk_class_teacher
        FOREIGN KEY (teacher_id)
        REFERENCES tblEmployees(employee_id),

    CONSTRAINT fk_class_room
        FOREIGN KEY (room_id)
        REFERENCES tblRooms(room_id),

    CONSTRAINT fk_class_slot
        FOREIGN KEY (slot_id)
        REFERENCES tblTimeSlots(slot_id),

    CONSTRAINT chk_class_students
        CHECK (
            current_students >= 0
            AND max_students > 0
            AND current_students <= max_students
        )
);


-- =========================================================
-- TIMETABLES
-- =========================================================

CREATE TABLE tblTimetables (
    timetable_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    class_id BIGINT NOT NULL,
    day_id BIGINT NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_timetable_class
        FOREIGN KEY (class_id)
        REFERENCES tblClasses(class_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_timetable_day
        FOREIGN KEY (day_id)
        REFERENCES tblDays(day_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_timetable
        UNIQUE (class_id, day_id)
);


-- =========================================================
-- ENROLLMENTS
-- =========================================================

CREATE TABLE tblEnrollments (
    enrollment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    student_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,

    price DECIMAL(10,2) NOT NULL,
    discount DECIMAL(10,2) DEFAULT 0,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,

    created_by BIGINT NULL,

    CONSTRAINT fk_enrollment_student
        FOREIGN KEY (student_id)
        REFERENCES tblStudents(student_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_enrollment_class
        FOREIGN KEY (class_id)
        REFERENCES tblClasses(class_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_enrollment_creator
        FOREIGN KEY (created_by)
        REFERENCES tblEmployees(employee_id)
        ON DELETE SET NULL,

    CONSTRAINT uq_student_class
        UNIQUE (student_id, class_id)
);


-- =========================================================
-- GRADES
-- =========================================================

CREATE TABLE tblGrade (
    grade_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    grade_name VARCHAR(50) NOT NULL,

    min_average DECIMAL(5,2),
    max_average DECIMAL(5,2),

    remark VARCHAR(100)
);


-- =========================================================
-- SCORE TYPES
-- =========================================================

CREATE TABLE tblScoreTypes (
    score_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    score_type_name VARCHAR(50) NOT NULL,

    percentage DECIMAL(5,2) DEFAULT 0
);


-- =========================================================
-- SCORES
-- =========================================================

CREATE TABLE tblScores (
    score_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    student_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    score_type_id BIGINT NOT NULL,

    score DECIMAL(5,2) NOT NULL DEFAULT 0,

    academic_year VARCHAR(20) NOT NULL,
    semester VARCHAR(50),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_score_student
        FOREIGN KEY (student_id)
        REFERENCES tblStudents(student_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_score_class
        FOREIGN KEY (class_id)
        REFERENCES tblClasses(class_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_score_type
        FOREIGN KEY (score_type_id)
        REFERENCES tblScoreTypes(score_type_id)
        ON DELETE CASCADE
);


-- =========================================================
-- STUDENT RESULTS
-- =========================================================

CREATE TABLE tblStudentResults (
    result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    student_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,

    academic_year VARCHAR(20) NOT NULL,

    total_score DECIMAL(6,2),
    average_score DECIMAL(5,2),

    grade_id BIGINT,

    CONSTRAINT fk_result_student
        FOREIGN KEY (student_id)
        REFERENCES tblStudents(student_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_result_class
        FOREIGN KEY (class_id)
        REFERENCES tblClasses(class_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_result_grade
        FOREIGN KEY (grade_id)
        REFERENCES tblGrade(grade_id)
        ON DELETE SET NULL
);


-- =========================================================
-- ATTENDANCES
-- =========================================================

CREATE TABLE tblAttendances (
    attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    enrollment_id BIGINT NOT NULL,

    attendance_date DATE NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'Absent',

    remarks VARCHAR(255),

    created_by BIGINT NULL,

    CONSTRAINT fk_attendance_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES tblEnrollments(enrollment_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_attendance_creator
        FOREIGN KEY (created_by)
        REFERENCES tblEmployees(employee_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_attendance
        UNIQUE (enrollment_id, attendance_date, created_by)
);


-- =========================================================
-- INVOICES
-- =========================================================

CREATE TABLE tblInvoices (
    invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    invoice_no VARCHAR(50) UNIQUE,

    student_id BIGINT NOT NULL,

    invoice_date DATE NOT NULL,

    total_amount DECIMAL(10,2) NOT NULL
        CHECK (total_amount >= 0),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    created_by BIGINT NOT NULL,

    status VARCHAR(50) DEFAULT 'Draft',

    CONSTRAINT fk_invoice_student
        FOREIGN KEY (student_id)
        REFERENCES tblStudents(student_id),

    CONSTRAINT fk_invoice_creator
        FOREIGN KEY (created_by)
        REFERENCES tblEmployees(employee_id)
);


-- =========================================================
-- PAYMENT METHODS
-- =========================================================

CREATE TABLE tblPaymentMethods (
    method_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    method_name VARCHAR(50) NOT NULL UNIQUE
);


-- =========================================================
-- PAYMENTS
-- =========================================================

CREATE TABLE tblPayments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    invoice_id BIGINT NOT NULL,

    payment_date DATE NOT NULL,

    amount DECIMAL(10,2) NOT NULL
        CHECK (amount > 0),

    payment_method_id BIGINT NOT NULL,

    reference_no VARCHAR(100),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    created_by BIGINT NOT NULL,

    status VARCHAR(50) DEFAULT 'Completed',

    CONSTRAINT fk_payment_invoice
        FOREIGN KEY (invoice_id)
        REFERENCES tblInvoices(invoice_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_payment_creator
        FOREIGN KEY (created_by)
        REFERENCES tblEmployees(employee_id),

    CONSTRAINT fk_payment_method
        FOREIGN KEY (payment_method_id)
        REFERENCES tblPaymentMethods(method_id)
);


-- =========================================================
-- INVOICE ITEMS
-- =========================================================

CREATE TABLE tblInvoiceItems (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    enrollment_id BIGINT NOT NULL,
    invoice_id BIGINT NOT NULL,

    description VARCHAR(200) NOT NULL,

    amount DECIMAL(10,2) NOT NULL
        CHECK (amount >= 0),

    CONSTRAINT fk_invoice_item_invoice
        FOREIGN KEY (invoice_id)
        REFERENCES tblInvoices(invoice_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_invoice_item_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES tblEnrollments(enrollment_id)
        ON DELETE CASCADE
);


-- =========================================================
-- ROLES
-- =========================================================

CREATE TABLE tblRoles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    role_name VARCHAR(50) UNIQUE NOT NULL,

    description VARCHAR(255)
);


-- =========================================================
-- PERMISSIONS
-- =========================================================

CREATE TABLE tblPermissions (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    permission_name VARCHAR(100) UNIQUE NOT NULL,

    description VARCHAR(255)
);


-- =========================================================
-- ROLE PERMISSIONS
-- =========================================================

CREATE TABLE tblRolePermissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,

    PRIMARY KEY (role_id, permission_id),

    CONSTRAINT fk_role_permission_role
        FOREIGN KEY (role_id)
        REFERENCES tblRoles(role_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_role_permission_permission
        FOREIGN KEY (permission_id)
        REFERENCES tblPermissions(permission_id)
        ON DELETE CASCADE
);


-- =========================================================
-- USERS
-- =========================================================

CREATE TABLE tblUsers (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference_id BIGINT NOT NULL,

    reference_type user_reference_type NOT NULL,

    username VARCHAR(100) NOT NULL UNIQUE,

    email VARCHAR(150) NOT NULL UNIQUE,

    password VARCHAR(255) NOT NULL,

    role_id BIGINT NOT NULL,

    status BOOLEAN DEFAULT TRUE,

    last_login TIMESTAMP NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    reset_token CHAR(64),
    reset_expiry TIMESTAMP,

    user_agent TEXT,

    ip_address VARCHAR(45),

    access_token VARCHAR(255),
    access_expiry TIMESTAMP,

    refresh_token CHAR(64),
    refresh_expiry TIMESTAMP,

    public_id VARCHAR(20) UNIQUE,

    CONSTRAINT fk_user_role
        FOREIGN KEY (role_id)
        REFERENCES tblRoles(role_id)
);

-- =========================================================
-- USER TOKENS
-- =========================================================

CREATE TABLE tblUserTokens (
    token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    -- Browser/device identifier
    device_id VARCHAR(100) NOT NULL,

    -- JWT ID (jti)
    jti UUID NOT NULL UNIQUE,

    -- Access JWT expiration
    access_expiry TIMESTAMPTZ NOT NULL,

    -- SHA-256 hash of the raw refresh token
    refresh_token CHAR(64) NOT NULL UNIQUE,

    -- Refresh token expiration
    refresh_expiry TIMESTAMPTZ NOT NULL,

    -- Human-readable device information
    device_info VARCHAR(255),

    -- Browser/client User-Agent
    user_agent TEXT,

    -- Client IP address
    ip_address VARCHAR(45),

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    revoked_at TIMESTAMPTZ NULL,

    CONSTRAINT fk_user_token_user
        FOREIGN KEY (user_id)
        REFERENCES tblUsers(user_id)
        ON DELETE CASCADE
);

-- =========================================================
-- INDEXES
-- =========================================================
CREATE INDEX idx_user_tokens_user_id
    ON tblUserTokens(user_id);

CREATE INDEX idx_user_tokens_access_token
    ON tblUserTokens(access_token);

CREATE INDEX idx_user_tokens_refresh_token
    ON tblUserTokens(refresh_token);

CREATE INDEX idx_user_tokens_access_expiry
    ON tblUserTokens(access_expiry);

CREATE INDEX idx_user_tokens_refresh_expiry
    ON tblUserTokens(refresh_expiry);


CREATE INDEX idx_employees_department
    ON tblEmployees(department_id);

CREATE INDEX idx_employees_phone
    ON tblEmployees(phone1);

CREATE INDEX idx_platforms_employee
    ON tblPlatforms(employee_id);

CREATE INDEX idx_students_created_by
    ON tblStudents(created_by);

CREATE INDEX idx_classes_course
    ON tblClasses(course_id);

CREATE INDEX idx_classes_subject
    ON tblClasses(subject_id);

CREATE INDEX idx_classes_teacher
    ON tblClasses(teacher_id);

CREATE INDEX idx_classes_room
    ON tblClasses(room_id);

CREATE INDEX idx_classes_slot
    ON tblClasses(slot_id);

CREATE INDEX idx_enrollments_student
    ON tblEnrollments(student_id);

CREATE INDEX idx_enrollments_class
    ON tblEnrollments(class_id);

CREATE INDEX idx_scores_student
    ON tblScores(student_id);

CREATE INDEX idx_scores_class
    ON tblScores(class_id);

CREATE INDEX idx_attendance_date
    ON tblAttendances(attendance_date);

CREATE INDEX idx_invoice_student
    ON tblInvoices(student_id);

CREATE INDEX idx_payment_invoice
    ON tblPayments(invoice_id);

CREATE INDEX idx_invoice_items_invoice
    ON tblInvoiceItems(invoice_id);

CREATE INDEX idx_users_reference
    ON tblUsers(reference_id, reference_type);
